main: alisolarflare.AliPresents
name: AliPresents
version: 2.0.1

commands:
  flairme:
    description: Activates the Flair Me Command. Ask Ali, she was tired when writing this description
  gpower:
    description: Testing command for ghostie powers
  powerup:
    description: Official g-power command that activates the ghostie powerups
  powerdown:
    description: Offical g-power command that deactivates the ghostie powerups
  pressalilink:
    description: Presses an Ali Link pressalilink frequency
  setalilink:
    description: Creates an Ali Link setalilink frequency
  cbgm0:
    description: Creative Boundaries Gamemode 0, allows players to return to survival
  cbgm1:
    description: Creative Boundaries Gamemode 1, allows players to access creative within their towns. Creative is removed outside of towns, so be careful
  setdickmode:
    description: Should players automatically return to creative when outside town borders? Dickmode says yes.
  joinminigame:
    description: Join a Button Minigame
  leaveminigame:
    description: Leave a button minigame
  listfighters:
    description: List all fighters currently in a button minigame
  setcolourspawn:
    description: sets the spawn points for each colour in a button minigame
  setmatchstate:
    description: sets the current state of the ultrahardcore game.
  addtouhc:
    description: Adds a player to the UltraHardcore match
  joinuhc:
    description: This command allows you to join an UltraHardcore match
  configurematch:
    description: Configures an UltraHardcore match
  schedulematch:
    description: Schedules an UltraHardcore match
  startmatch:
    description: Starts an UltraHardcore match
  spreadplayers:
    description: Admin command that spreads players around an ultrahardcore match
  teleporttouhc:
    description: Teleports you to the ultrahardcore match
  setuhclobby:
    description: Sets the area where a uhc will take place
  activatepowers:
    description: Admin command that activates gpowers on a uhc
  setworldborders:
    description: sets the worldborders to a uhc match
