main: alisolarflare.AliPresents
name: AliPresents
version: 2.0.0

commands:
  alishulker:
    description: Spawns a shulker at player location Alishulker health withereffect invisibility true experiencedrops
  pressalilink:
    description: Presses an Ali Link pressalilink frequency
  setalilink:
    description: Creates an Ali Link setalilink frequency
  setFlairDoorColour:
    description: Sets the flair door colour mode, when lighting portals